### ISSUE TITLE
Compilation error on ParamsClient

### ISSUE THREAD

**Issue by cblmemo** [Hsword/SpotServe#7]
When I try to compile the `ParamsClient`, I got the following type conversion error:

```bash
$ make -j
Scanning dependencies of target memory_utils
[ 10%] Built target matrix_transpose_kernels
[ 16%] Built target cJSON
[ 23%] Built target tcp_utils
[ 33%] Built target mpi_utils
[ 36%] Building CUDA object src/utils/CMakeFiles/memory_utils.dir/memory_utils.cu.o
[ 53%] Built target simple_share
[ 56%] Built target nccl_utils
/home/ubuntu/SpotServe/ParamsClient/src/utils/memory_utils.cu(73): warning #186-D: pointless comparison of unsigned integer with zero
      myAssert(size >= 0, "/home/ubuntu/SpotServe/ParamsClient/src/utils/memory_utils.cu", 73, "Ask deviceMalloc size " + std::to_string(size) + "< 0 is invalid.");
                    ^

Remark: The warnings can be suppressed with "-diag-suppress <warning-number>"

/home/ubuntu/SpotServe/ParamsClient/src/utils/memory_utils.cu(73): warning #186-D: pointless comparison of unsigned integer with zero
      myAssert(size >= 0, "/home/ubuntu/SpotServe/ParamsClient/src/utils/memory_utils.cu", 73, "Ask deviceMalloc size " + std::to_string(size) + "< 0 is invalid.");
                    ^

Remark: The warnings can be suppressed with "-diag-suppress <warning-number>"

/home/ubuntu/SpotServe/ParamsClient/src/utils/memory_utils.cu(516): error: more than one conversion function from "half" to a built-in type applies:
            function "__half::operator float() const" (declared at line 217 of /usr/local/cuda/bin/../targets/x86_64-linux/include/cuda_fp16.hpp)
            function "__half::operator short() const" (declared at line 235 of /usr/local/cuda/bin/../targets/x86_64-linux/include/cuda_fp16.hpp)
            function "__half::operator unsigned short() const" (declared at line 238 of /usr/local/cuda/bin/../targets/x86_64-linux/include/cuda_fp16.hpp)
            function "__half::operator int() const" (declared at line 241 of /usr/local/cuda/bin/../targets/x86_64-linux/include/cuda_fp16.hpp)
            function "__half::operator unsigned int() const" (declared at line 244 of /usr/local/cuda/bin/../targets/x86_64-linux/include/cuda_fp16.hpp)
            function "__half::operator long long() const" (declared at line 247 of /usr/local/cuda/bin/../targets/x86_64-linux/include/cuda_fp16.hpp)
            function "__half::operator unsigned long long() const" (declared at line 250 of /usr/local/cuda/bin/../targets/x86_64-linux/include/cuda_fp16.hpp)
            function "__half::operator __nv_bool() const" (declared at line 254 of /usr/local/cuda/bin/../targets/x86_64-linux/include/cuda_fp16.hpp)
          tmp_val = tmp_val * (T_fake_type)(1.0f);
                    ^
          detected during:
            instantiation of "void fastertransformer::fakeCast<T_IN,T_fake_type>(T_IN *, size_t) [with T_IN=float, T_fake_type=half]" at line 526
            instantiation of "void fastertransformer::invokeFakeCast<T_IN,T_fake_type>(T_IN *, size_t, cudaStream_t) [with T_IN=float, T_fake_type=half]" at line 535

/home/ubuntu/SpotServe/ParamsClient/src/utils/memory_utils.cu(516): error: more than one conversion function from "half" to a built-in type applies:
            function "__half::operator float() const" (declared at line 217 of /usr/local/cuda/bin/../targets/x86_64-linux/include/cuda_fp16.hpp)
            function "__half::operator short() const" (declared at line 235 of /usr/local/cuda/bin/../targets/x86_64-linux/include/cuda_fp16.hpp)
            function "__half::operator unsigned short() const" (declared at line 238 of /usr/local/cuda/bin/../targets/x86_64-linux/include/cuda_fp16.hpp)
            function "__half::operator int() const" (declared at line 241 of /usr/local/cuda/bin/../targets/x86_64-linux/include/cuda_fp16.hpp)
            function "__half::operator unsigned int() const" (declared at line 244 of /usr/local/cuda/bin/../targets/x86_64-linux/include/cuda_fp16.hpp)
            function "__half::operator long long() const" (declared at line 247 of /usr/local/cuda/bin/../targets/x86_64-linux/include/cuda_fp16.hpp)
            function "__half::operator unsigned long long() const" (declared at line 250 of /usr/local/cuda/bin/../targets/x86_64-linux/include/cuda_fp16.hpp)
            function "__half::operator __nv_bool() const" (declared at line 254 of /usr/local/cuda/bin/../targets/x86_64-linux/include/cuda_fp16.hpp)
          tmp_val = tmp_val * (T_fake_type)(1.0f);
                              ^
          detected during:
            instantiation of "void fastertransformer::fakeCast<T_IN,T_fake_type>(T_IN *, size_t) [with T_IN=float, T_fake_type=half]" at line 526
            instantiation of "void fastertransformer::invokeFakeCast<T_IN,T_fake_type>(T_IN *, size_t, cudaStream_t) [with T_IN=float, T_fake_type=half]" at line 535

2 errors detected in the compilation of "/home/ubuntu/SpotServe/ParamsClient/src/utils/memory_utils.cu".
make[2]: *** [src/utils/CMakeFiles/memory_utils.dir/build.make:63: src/utils/CMakeFiles/memory_utils.dir/memory_utils.cu.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:343: src/utils/CMakeFiles/memory_utils.dir/all] Error 2
make: *** [Makefile:84: all] Error 2
```

Environment version:

```bash
$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Mon_Apr__3_17:16:06_PDT_2023
Cuda compilation tools, release 12.1, V12.1.105
Build cuda_12.1.r12.1/compiler.32688072_0
$ nvidia-smi
Mon Oct  7 16:56:36 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.12             Driver Version: 535.104.12   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       On  | 00000000:00:1B.0 Off |                    0 |
| N/A   25C    P8               9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
|   1  Tesla T4                       On  | 00000000:00:1C.0 Off |                    0 |
| N/A   25C    P8               8W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
|   2  Tesla T4                       On  | 00000000:00:1D.0 Off |                    0 |
| N/A   25C    P8               8W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
|   3  Tesla T4                       On  | 00000000:00:1E.0 Off |                    0 |
| N/A   25C    P8               9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|  No running processes found                                                           |
+---------------------------------------------------------------------------------------+
```

**Comment by SpiritedAwayCN** [comment]
This cutlass problem can also be found in: https://github.com/NVIDIA/cutlass/issues/4, and other projects such as  https://github.com/LLMServe/SwiftTransformer/issues/5. 

You may change CUDA arch flags when compiling.

**Comment by cblmemo** [comment]
> This cutlass problem can also be found in: [NVIDIA/cutlass#4](https://github.com/NVIDIA/cutlass/issues/4), and other projects such as [LLMServe/SwiftTransformer#5](https://github.com/LLMServe/SwiftTransformer/issues/5).
> 
> You may change CUDA arch flags when compiling.

Thanks! This resolved the problem for me.
